//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpDemo.PIClient.PIClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:gmk:tm_v1", ConfigurationName="PIClient.SI_TM2NET_Out")]
    public interface SI_TM2NET_Out {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CSharpDemo.PIClient.PIClient.SI_TM2NET_OutRequest SI_TM2NET_Out(CSharpDemo.PIClient.PIClient.SI_TM2NET_OutRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<CSharpDemo.PIClient.PIClient.SI_TM2NET_OutRequest> SI_TM2NET_OutAsync(CSharpDemo.PIClient.PIClient.SI_TM2NET_OutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:gmk:tm_v1")]
    public partial class DT_TM2NET : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wFIDField;
        
        private string pointField;
        
        private string xmlKeyField;
        
        private string xmlDataInField;
        
        private string xmlDataOutField;
        
        private string xmlExField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WFID {
            get {
                return this.wFIDField;
            }
            set {
                this.wFIDField = value;
                this.RaisePropertyChanged("WFID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
                this.RaisePropertyChanged("Point");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string XmlKey {
            get {
                return this.xmlKeyField;
            }
            set {
                this.xmlKeyField = value;
                this.RaisePropertyChanged("XmlKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XmlDataIn {
            get {
                return this.xmlDataInField;
            }
            set {
                this.xmlDataInField = value;
                this.RaisePropertyChanged("XmlDataIn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string XmlDataOut {
            get {
                return this.xmlDataOutField;
            }
            set {
                this.xmlDataOutField = value;
                this.RaisePropertyChanged("XmlDataOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string XmlEx {
            get {
                return this.xmlExField;
            }
            set {
                this.xmlExField = value;
                this.RaisePropertyChanged("XmlEx");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_TM2NET_OutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:gmk:tm_v1", Order=0)]
        public CSharpDemo.PIClient.PIClient.DT_TM2NET MT_TM2NET;
        
        public SI_TM2NET_OutRequest() {
        }
        
        public SI_TM2NET_OutRequest(CSharpDemo.PIClient.PIClient.DT_TM2NET MT_TM2NET) {
            this.MT_TM2NET = MT_TM2NET;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_TM2NET_OutChannel : CSharpDemo.PIClient.PIClient.SI_TM2NET_Out, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_TM2NET_OutClient : System.ServiceModel.ClientBase<CSharpDemo.PIClient.PIClient.SI_TM2NET_Out>, CSharpDemo.PIClient.PIClient.SI_TM2NET_Out {
        
        public SI_TM2NET_OutClient() {
        }
        
        public SI_TM2NET_OutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_TM2NET_OutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_TM2NET_OutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_TM2NET_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSharpDemo.PIClient.PIClient.SI_TM2NET_OutRequest CSharpDemo.PIClient.PIClient.SI_TM2NET_Out.SI_TM2NET_Out(CSharpDemo.PIClient.PIClient.SI_TM2NET_OutRequest request) {
            return base.Channel.SI_TM2NET_Out(request);
        }
        
        public void SI_TM2NET_Out(ref CSharpDemo.PIClient.PIClient.DT_TM2NET MT_TM2NET) {
            CSharpDemo.PIClient.PIClient.SI_TM2NET_OutRequest inValue = new CSharpDemo.PIClient.PIClient.SI_TM2NET_OutRequest();
            inValue.MT_TM2NET = MT_TM2NET;
            CSharpDemo.PIClient.PIClient.SI_TM2NET_OutRequest retVal = ((CSharpDemo.PIClient.PIClient.SI_TM2NET_Out)(this)).SI_TM2NET_Out(inValue);
            MT_TM2NET = retVal.MT_TM2NET;
        }
        
        public System.Threading.Tasks.Task<CSharpDemo.PIClient.PIClient.SI_TM2NET_OutRequest> SI_TM2NET_OutAsync(CSharpDemo.PIClient.PIClient.SI_TM2NET_OutRequest request) {
            return base.Channel.SI_TM2NET_OutAsync(request);
        }
    }
}
